### ISSUE TITLE
No Pull request template available!

### ISSUE THREAD

**Issue by madm234** [karantec/cateringWebsiteSanjay#11]
I can make a PR template including suggestions, rules and checkboxes so that every PR will be easily understandable to viewers.

**Comment by karantec** [comment]
Sure wait till 12 pm

**Comment by madm234** [comment]
You said wait and there's still no update from your side. If you want this then please put it under hactoberfest and assign me

**Comment by karantec** [comment]
yes sure
you start the work

**Comment by karantec** [comment]
Actually I was busy in works , as i am able to see the messages
