### ISSUE TITLE
Unresponsive Active option in the navbar

### ISSUE THREAD

**Issue by madm234** [karantec/cateringWebsiteSanjay#9]
### **If I'm clicking on Gallery or any other navbar option other than 'Home'; it still shows the 'Home' button active instead of the clicked one. As you can see in then attached image, I'm in the gallery section however still home button is active rather than gallery button.**

<img width="944" alt="image" src="https://github.com/karantec/cateringWebsiteSanjay/assets/88799492/d809b127-36c3-446c-9e7d-07a3d710d1ca">

**Comment by madm234** [comment]
@karantec Hi. Can you put this issue under HacoberFest

**Comment by karantec** [comment]
wait for today ninght

**Comment by karantec** [comment]
ye sure

**Comment by karantec** [comment]
make a correct active link for each page in the website

**Comment by madm234** [comment]
> make a correct active link for each page in the website

Ok sure.

**Comment by madm234** [comment]
@karantec hi karan. I have already submitted my pr likely a week ago for this problem and see what I got. 

![Screenshot_2023-10-08-15-00-33-478_com android chrome](https://github.com/karantec/cateringWebsiteSanjay/assets/88799492/34430006-9e21-4470-91d1-41c9ca01f929)

If you are not participanting  in hactoberfest then you should remove hactoberfest labels from all your issues. If I'm missing something here, then do address the problem from your side.

**Comment by karantec** [comment]
I am participating  bro

**Comment by karantec** [comment]
let me check bro
 projects is already tagged with hacktoberfest

**Comment by madm234** [comment]
You can read the full message
![IMG_20231008_151429](https://github.com/karantec/cateringWebsiteSanjay/assets/88799492/ec2a0709-9af4-4f78-8d73-4dfdab37a15c)

And also if there's any problem with the pr or any advancement you want just let me know. But take some action bro. Thanks

**Comment by karantec** [comment]
wait a second

**Comment by karantec** [comment]
Sorry for the interruption bro , It a spelling error in topics I Has done
corrected the  topic spelling
and thanks for the issue you have pointed out. I have lots of work I would
not able to see that ..

**Comment by madm234** [comment]
@karantec yes now status has been changed. Thnks karan. I would not ask for much as u r busy rn but do look at the pr I have raised for merge. There's no conflict and problem has been solved too. 
This is my first open source contribution. I just want a hactoberfest badge. See if you can merge that. 
Thnks again

**Comment by karantec** [comment]
yes bro you problem has solve bro na

**Comment by madm234** [comment]
@karantec No bro. My pr #10 has not been merged. 
That's my only problem. I have already mentioned above. 
 
![IMG_20231008_164844](https://github.com/karantec/cateringWebsiteSanjay/assets/88799492/0f539d72-11d9-43c9-a667-5a18a84d839c)

**Comment by karantec** [comment]
I already merge your pr

**Comment by karantec** [comment]
but I think i have updated things it takes some time wait for some time it got correct in some time

**Comment by madm234** [comment]
> but I think i have updated things it takes some time wait for some time it got correct in some time

ok sure .Thank you
